specVersion: 1.0.0
name: Controller
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Controller Reverse Mapping testing

repository: https://github.com/shreyas3336/SubQuery
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: >-
    wss://acala-mandala.api.onfinality.io/ws?apikey=2267b431-9138-4602-8f50-a4ea1dcd3951
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1332000
    # processor:
    #   file: ./dist/acalaEvm.js
    #   options:
    #     abi: controller
    #     address: '0x9C27C76239E69555103C43AFD87C41628E8f8a14'
    # assets:
    #   controller:
    #     file: ./abi/Controller.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleProjectInfo
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - ProjectInfo(address indexed tokenAddress,string tokenTicker,address creator,uint256 tokenDecimal)
        - handler: handleCreateVest
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - CreateVest(address indexed assetAddress,address creator,address userAddress,uint256 userAmount,uint256 unlockTime,address wrappedERC20Address,string wrappedAssetTicker,bool transferable)
        - handler: handleTransferWrapped
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
                - TransferWrapped(address userAddress,address indexed wrappedTokenAddress,address receiverAddress,uint256 amount)
        - handler: handleWithdraw
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
                - Withdraw(address indexed userAddress,uint256 amount,address wrappedTokenAddress)
