specVersion: 1.0.0
name: Master
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Master Subgraph
repository: https://github.com/shreyas3336/SubQuery
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: >-
    wss://acala-mandala.api.onfinality.io/ws?apikey=2267b431-9138-4602-8f50-a4ea1dcd3951
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1359500
    processor:
      file: ./dist/acalaEvm.js
      options:
        abi: master
        address: '0x69a6A5dBBc0afeC6B29D35B6AD1F23a334ef6a4d'
    assets:
      master:
        file: ./abi/Master.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleProjectInfo
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - ProjectInfo(string name,address indexed tokenAddress,string tokenTicker,string documentHash,address creator,uint256 tokenDecimal)
        - handler: handleUpgraded
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Upgraded(address indexed implementation)
  - kind: substrate/AcalaEvm
    startBlock: 1359500
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAcalaEvmEvent
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
            
