specVersion: 1.0.0
name: Inc
version: 0.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: A basic Acala EVM example
repository: https://github.com/shreyas3336/SubQuery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: wss://mandala-tc7-rpcnode.aca-dev.network/ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1000000
    processor:
      file: ./dist/acalaEvm.js
      options:
        abi: erc20
        address: '0x66362069f0185fe02c948307f1cceb9c356b8b77'
    assets:
      erc20:
        file: ./abi/Inc.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleIncrement
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Increment(address indexed initiator, uint value)
              - CapxIncrement(address indexed initiator, uint value)
