specVersion: 1.0.0
name: Mint
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Metadata for Mint
repository: https://github.com/shreyas3336/SubQuery
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: wss://mandala-tc7-rpcnode.aca-dev.network/ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1415507
    processor:
      file: ./dist/acalaEvm.js
      options:
        abi: factory
        address: '0xC1Ae4776FA9cC3e780dFb321CaA45A52926381D5'
    assets:
      factory:
        file: ./abis/Factory.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewTokenDeployed
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewTokenDeployed(uint256,address,string,address)
        - handler: handleNewImplementation
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewERC20Implementation(string,uint256,address,bool,bool[4])
