specVersion: 1.0.0
name: Inc
version: v0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: SubQuery Testing
repository: https://github.com/shreyas3336/SubQuery
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: wss://mandala-tc7-rpcnode.aca-dev.network/ws
  startBlock: 1332174
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1000000
    processor:
      file: ./dist/acalaEvm.js
      options:
        abi: erc20
        address: '0x0000000000000000000100000000000000000000'
    assets:
      erc20:
        file: ./erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAcalaEvmEvent
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Increment(address indexed initiator, uint value)
              - CapxIncrement(address indexed initiator, uint value)
